In [1]:
# This is all the code and exercise solutions for Python advanced module

In [2]:
# importing Math module
import math

In [3]:
x = math.sqrt(36)
y = math.pi
print(x)
print(y)


6.0
3.141592653589793


In [4]:
# importing a common Python library
import numpy as np

In [8]:
# importing a common Python library

import matplotlib.pyplot as plt
from matplotlib import pyplot as plt


In [9]:
def add_function(a, b):
	result = a + b
	return result

z = add_function(20, 22)
print(z)


42


In [10]:
# example_module.py

def add(a, b):
    # add two numbers
    return(a + b)

def subtract(a, b):
    # subtract two numbers
    return(a - b)


In [12]:
# solution to exercise 2.1
# math_module.py

# Function to add two numbers
def add(a, b):
    return a + b

# Function to subtract two numbers
def subtract(a, b):
    return a - b

# Function to multiply two numbers
def multiply(a, b):
    return a * b

# Function to divide two numbers
def divide(a, b):
    if b != 0:
        return a / b
    else:
        return "Error: Division by zero is not allowed."

In [14]:
# math_script.py
# You will get module error if you don't create math_module.py in the same directory first!

# Importing functions from math_module.py
import math_module

# Choose two numbers
num1 = 10
num2 = 5

# Run each function and print the result
print(f"The sum of {num1} and {num2} is: {math_module.add(num1, num2)}")
print(f"The difference of {num1} and {num2} is: {math_module.subtract(num1, num2)}")
print(f"The product of {num1} and {num2} is: {math_module.multiply(num1, num2)}")
print(f"The division of {num1} by {num2} is: {math_module.divide(num1, num2)}")

ModuleNotFoundError: No module named 'math_module'

In [16]:
# calling functions from a common Python library
normal_sample = np.random.normal(loc=0.0, scale=1.0, size=10)
integer_sample = np.random.randint(low = 10, high=None, size=5)
print (normal_sample)
print (integer_sample)

[ 1.07251675 -1.29823897 -1.03667736  0.36740703 -0.31536088  0.71880342
 -0.77226428 -0.04965569 -0.50161291 -1.08507481]
[4 3 4 3 5]


In [17]:
# numpy library
import numpy as np

In [18]:
#using a list to create a NumPy array
list_array = np.array([1, 2, 3, 4, 5])
print(list_array)
print(type(list_array))


[1 2 3 4 5]
<class 'numpy.ndarray'>


In [19]:
#using a tuple to create a NumPy array
tuple_array = np.array((1, 2, 3, 4, 5))
print(tuple_array)
print(type(tuple_array))


[1 2 3 4 5]
<class 'numpy.ndarray'>


In [20]:
#0-D array 
array_0d = np.array(36)
print(array_0d)


36


In [21]:
# This is a 1-D array containing the values 1,2,3,4,5.
array_1d = np.array([1, 2, 3, 4, 5])
print(array_1d)


[1 2 3 4 5]


In [22]:
# Create a 2-D array containing two arrays with the values 1,2,3 and 4,5,6:

array_2d = np.array([[1, 2, 3], [4, 5, 6]])
print(array_2d)


[[1 2 3]
 [4 5 6]]


In [23]:
# using ndim to determine dimensions of an array

array_0d = np.array(36)
array_1d = np.array([1, 2, 3, 4, 5])
array_2d = np.array([[1, 2, 3], [4, 5, 6]])
array_3d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print("number of dimensions for array_0d is", array_0d.ndim)
print("number of dimensions for array_1d is", array_1d.ndim)
print("number of dimensions for array_2d is", array_2d.ndim)
print("number of dimensions for array_3d is", array_3d.ndim)


number of dimensions for array_0d is 0
number of dimensions for array_1d is 1
number of dimensions for array_2d is 2
number of dimensions for array_3d is 3


In [24]:
# using np.arange
# Creating an array from 0 to 9 (excluding 10):

arr = np.arange(10)
print(arr)


[0 1 2 3 4 5 6 7 8 9]


In [25]:
# using np.linspace
# Generate 20 evenly spaced samples between 0 and 40, not including 40
samples = np.linspace(0, 40, num=20, endpoint=False)
print(samples)


[ 0.  2.  4.  6.  8. 10. 12. 14. 16. 18. 20. 22. 24. 26. 28. 30. 32. 34.
 36. 38.]


In [26]:
# using shape to find the number of elements in each dimension

arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print(arr.shape)


(2, 4)


In [27]:
# using reshape to change dimension structure of an array

# Create a 1D array
data = np.arange(12)  
# Array containing 12 elements (0 to 11)

# Reshape into a 2D array with 3 rows and 4 columns
reshaped_data = data.reshape(3, 4)

# Print the original and reshaped arrays
print("Original 1D array:\n", data)
print("\nReshaped 2D array:\n", reshaped_data)


Original 1D array:
 [ 0  1  2  3  4  5  6  7  8  9 10 11]

Reshaped 2D array:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [28]:
# solution to exercise 3.1
Array_example = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]

# Convert to a 2-D array with 4 rows and 3 columns
Array_2D = np.reshape(Array_example, (4, 3))

print(Array_2D)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [29]:
# NumPy array indexing
#Array indexing in 1-D arrays
array_numbers = np.array([1, 2, 3, 4])
print(array_numbers[0])


1


In [30]:
#Array value assignment 
array_numbers = np.array([1, 2, 3, 4])
array_numbers[0]=6
print(array_numbers)


[6 2 3 4]


In [31]:
#Array indexing in 2-D arrays
array_numbers2 = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print(array_numbers2)
# Access the element on the first row, second column:
print('2nd element on 1st row: ', array_numbers2[0, 1])
# Access the element on the 2nd row, 5th column:
print('5th element on 2nd row: ', array_numbers2[1, 4])


[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
2nd element on 1st row:  2
5th element on 2nd row:  10


In [32]:
# solution to exercise 4.1
# Create a 2-D 5x5 array using np.arange()
array_2d = np.arange(1, 26).reshape(5, 5)

# Print the element in the third row and second column
element = array_2d[2, 1]  # Indexing starts from 0, so this is the third row, second column
print(element)

12


In [33]:
#Slice elements from index 1 to index 5 from the following array
array_example = np.array([1, 2, 3, 4, 5, 6, 7])
print(array_example[1:5])


[2 3 4 5]


In [34]:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
#Slice a 2-D array, from the second element, slice elements from index 1 to index 4
print(arr[1, 1:4])
#From both elements, slice index 1 to index 4 (not included), this will return a 2-D array:
print(arr[0:2, 1:4])


[7 8 9]
[[2 3 4]
 [7 8 9]]


In [35]:
# Join two 1-D arrays

arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr_combined = np.concatenate((arr1, arr2))
print(arr_combined) 


[1 2 3 4 5 6]


In [36]:
# Create two NumPy arrays
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

# Add the arrays element-wise using the + operator
sum_arr = arr1 + arr2
print("Element-wise sum:\n", sum_arr) 

# Multiplication is done the same way as addition
product_arr = arr1 * arr2
print("Element-wise product:\n", product_arr)

#If the arrays have different shapes, NumPy might perform broadcasting to make them compatible for element-wise operations. Broadcasting extends the smaller array in a specific way to match the dimensions of the larger array.

arr3 = np.array([1, 2, 3])
arr4 = np.array([10])

# Add arr3 (with 3 elements) to arr4 (with 1 element)
combined = arr3 + arr4
print("broadcasting example sum is: \n", combined)

combined_product = arr3 * arr4
print("broadcasting example product is: \n", combined_product)


Element-wise sum:
 [5 7 9]
Element-wise product:
 [ 4 10 18]
broadcasting example sum is: 
 [11 12 13]
broadcasting example product is: 
 [10 20 30]


In [38]:
# solution to exercise 4.2
array = np.array([1, 3, 4, 5])

# Perform the arithmetic calculations
result1 = 2 * array  # 2 * array
result2 = array * array  # array * array
array2 = np.array([2, 4])  # Define the array [2, 4]

# Repeat the elements of array2 to match the shape of array for element-wise multiplication
array2_broadcasted = np.tile(array2, 2)  # Repeats array2 to get the shape (4,)
result3 = array2_broadcasted * array  # element-wise multiplication with broadcasting

print(result1)
print(result2)
print(result3)

[ 2  6  8 10]
[ 1  9 16 25]
[ 2 12  8 20]


In [40]:
# NumPy Stats functions

X = np.array( [ [-2.5, 3.1, 7],
                [10, 11, 12] ] )
print("mean = ", X.mean())
print("Variance = ", X.var())
print("Standard Deviation = ", X.std())
print("min = ", X.min())
print("max = ", X.max())
print("sum = ", X.sum())
print("product = ", X.prod())

mean =  6.766666666666667
Variance =  25.855555555555554
Standard Deviation =  5.084835843520964
min =  -2.5
max =  12.0
sum =  40.6
product =  -71610.0


In [41]:
# Generate a random integer from 0 to 100:

from numpy import random

x = random.randint(100)

print(x)

78


In [42]:
# Generate a 1-D array containing 5 random integers from 0 to 100:

x=random.randint(100, size=(5))

print(x)

[98 53 21 30 14]


In [43]:
# Generate a 2-D array with 3 rows, each row containing 5 random integers from 0 to 100:

x = random.randint(100, size=(3, 5))

print(x)

[[38 30 50 58 22]
 [91  0 57 33 34]
 [38 95  0  1 40]]


In [45]:
# Generate a 1-D array containing 100 values, where each value has to be 3, 5, 7 or 9.

#The probability for the value to be 3 is set to be 0.1
#The probability for the value to be 5 is set to be 0.3
#The probability for the value to be 7 is set to be 0.6
#The probability for the value to be 9 is set to be 0

x = random.choice([3, 5, 7, 9], p=[0.1, 0.3, 0.6, 0.0], size=(100))

print(x)

[5 7 7 5 7 3 7 7 7 7 7 7 5 7 7 7 7 7 7 7 7 7 7 3 5 5 7 7 5 7 7 7 5 5 7 5 7
 7 5 5 7 7 7 7 7 7 5 7 7 7 3 7 7 7 5 7 7 7 5 3 5 7 7 7 7 7 7 5 7 3 5 7 7 7
 7 7 7 7 7 7 7 7 7 5 7 7 5 7 5 7 5 3 3 7 5 5 5 3 5 5]


In [46]:
# Generate a random normal distribution of size 2x3:

from numpy import random

x = random.normal(size=(2, 3))

print(x)

[[ 0.69944795  0.79310018 -1.21294537]
 [-0.96039136 -1.3596002  -0.90730678]]


In [47]:
# Generate a random normal distribution of size 2x3 with mean at 1 and standard deviation of 2:

from numpy import random

x = random.normal(loc=1, scale=2, size=(2, 3))

print(x)

[[-1.29961025  2.55141801  1.54792755]
 [ 6.1647411   0.20325499 -2.18054253]]


In [48]:
# SciPy library
# import constants from SciPy library 
# Then use pi constant, giga and nano conversion constants, and foot and yard conversion constants.

from scipy import constants
print(constants.pi)
print(constants.giga)
print(constants.nano)
print(constants.foot)
print(constants.yard)


3.141592653589793
1000000000.0
1e-09
0.30479999999999996
0.9143999999999999


In [49]:
print(dir(constants))

['Avogadro', 'Boltzmann', 'Btu', 'Btu_IT', 'Btu_th', 'ConstantWarning', 'G', 'Julian_year', 'N_A', 'Planck', 'R', 'Rydberg', 'Stefan_Boltzmann', 'Wien', '__all__', '__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__path__', '__spec__', '_codata', '_constants', '_obsolete_constants', 'acre', 'alpha', 'angstrom', 'arcmin', 'arcminute', 'arcsec', 'arcsecond', 'astronomical_unit', 'atm', 'atmosphere', 'atomic_mass', 'atto', 'au', 'bar', 'barrel', 'bbl', 'blob', 'c', 'calorie', 'calorie_IT', 'calorie_th', 'carat', 'centi', 'codata', 'constants', 'convert_temperature', 'day', 'deci', 'degree', 'degree_Fahrenheit', 'deka', 'dyn', 'dyne', 'e', 'eV', 'electron_mass', 'electron_volt', 'elementary_charge', 'epsilon_0', 'erg', 'exa', 'exbi', 'femto', 'fermi', 'find', 'fine_structure', 'fluid_ounce', 'fluid_ounce_US', 'fluid_ounce_imp', 'foot', 'g', 'gallon', 'gallon_US', 'gallon_imp', 'gas_constant', 'gibi', 'giga', 'golden', 'golden_ratio', 'grain', '

In [50]:
# Find root of the equation x + cos(x): 

from scipy.optimize import root
from math import cos

def eqn(x):
  return x + cos(x)

myroot = root(eqn, 0)

print(myroot.x)
print(myroot)


[-0.73908513]
 message: The solution converged.
 success: True
  status: 1
     fun: [ 0.000e+00]
       x: [-7.391e-01]
    nfev: 9
    fjac: [[-1.000e+00]]
       r: [-1.674e+00]
     qtf: [-2.668e-13]


C:\Users\yemon\AppData\Local\Temp\ipykernel_2948\3306016120.py:7: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  return x + cos(x)


In [51]:
from scipy.optimize import minimize

def eqn(x):
  return x**2 + x + 2

mymin = minimize(eqn, 0, method='BFGS')

print(mymin)


  message: Optimization terminated successfully.
  success: True
   status: 0
      fun: 1.75
        x: [-5.000e-01]
      nit: 2
      jac: [ 0.000e+00]
 hess_inv: [[ 5.000e-01]]
     nfev: 8
     njev: 4
